### ISSUE TITLE
Errors while compiling nvme_test

### ISSUE THREAD

**Issue by pietrobressana** [cambridgehackers/connectal#129]
Hi,

the following error appears while compiling nvme_test with command "make build.nfsume":

Error: "/home/netfpga/gitHub/connectal/lib/nvme/bsv/Nvme.bsv", line 166, column 62: (T0080)
  Type error at the use of the following function:
    toGet

  The expected return type of the function:
    Clock

  The return type according to the use:
    GetPut::Get#(b__)

obj/Makefile:38: recipe for target 'obj/Nvme.bo' failed
make[1]: *** [obj/Nvme.bo] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by jameyhicks** [comment]
Commit 04744b6812dc1718ed9cf75af76b96fd651b5291 fixes this problem, although it still does not work on NFSUME.
