### ISSUE TITLE
Bypass version mismatch problems in generated Makefile

### ISSUE THREAD

**Issue by rajat-agarwal-** [cambridgehackers/connectal#158]
Hello,
Is there a way in connectal, where i don't check files for their versions, and build directly with bsc compiler.(Hopefully a place to decide whether to insert -u flag or not).
Incidentally, I have some previously compiled .bo files(unfortunately their source files are not available.) which are required. Now if i run connectal directly, It does a version check and throws error stating that binary versions doesn't match, need to recompile. Is there a way to solve this problem. 
Attached log files.
[log.txt](https://github.com/cambridgehackers/connectal/files/4244234/log.txt)

**Comment by jameyhicks** [comment]
That message is from the bsc compiler. I don't know of any way to bypass it.

I usually clean old .bo versions whenever I change versions of bsc.
