### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by CyanoKobalamyne** [cambridgehackers/connectal#178]
Is there any intention to add Python 3 support, given that Python 2 has been deprecated? The main scripts run with just changing `x.has_key(y)` to `y in x`, but there are some other things in scripts I don't personally use (some remaining `print` statements, `cStringIO` imports, implicit relative imports, `xrange`, etc.).

**Comment by jameyhicks** [comment]
Yes, I would like to switch it all over to python3, but I have not had much time to work on it recently.

**Comment by CyanoKobalamyne** [comment]
I made an attempt in #179. It is not quite converting the code to Python 3 but at least making it compatible with the changes in 3.0.

**Comment by jameyhicks** [comment]
Thank you for the PRs fixing this issue.

Going forward, I think it would be OK to require python3 and drop support for python2.

**Comment by CyanoKobalamyne** [comment]
Makes sense. I guess I wasn't sure how many people were using Connectal with Python 2.
