### ISSUE TITLE
ERROR: could not insert 'portalmem'

### ISSUE THREAD

**Issue by manish-pp** [cambridgehackers/connectal#191]
manish@manish:~/Desktop/Connectal/connectal$ sudo modprobe portalmem
[sudo] password for manish: 
modprobe: ERROR: could not insert 'portalmem': Operation not permitted

In the step of installing drivers (**Preparation for Kintex and Virtex boards**), "**sudo modprobe portalmem**" command is giving the above error. Please help me resolve the error.

**Comment by jameyhicks** [comment]
I think if you run `dmesg` you will find that your kernel has updated since you built portalmem.ko. If so, rebuild the module and you should be able to insmod / modprobe the module.

**Comment by manish-pp** [comment]
> I think if you run `dmesg` you will find that your kernel has updated since you built portalmem.ko. If so, rebuild the module and you should be able to insmod / modprobe the module.

I disabled the "Secure Boot" in BIOS setting, now I am not getting any error but there is not output also.
