### ISSUE TITLE
add python-netifaces as a dependence

### ISSUE THREAD

**Issue by jameyhicks** [cambridgehackers/connectal#53]
Needed by run.zedboard when it is discovering devices on the network.

**Comment by jameyhicks** [comment]
Updated debian/control, will be fixed next time I publish packages.

**Comment by jankcorn** [comment]
also please add python-gflags  (needed by python adb, used by ...)

**Comment by jameyhicks** [comment]
Fixed for Ubuntu with 15.02.5 (both python-netifaces and python-gflags)
And CentOS, but python-gflags is called "python-python-gflags".

**Comment by jameyhicks** [comment]
and also adding python-gmpy, which is used by pcie trace decode, but somehow fell off the list of dependences.

**Comment by jameyhicks** [comment]
Verified in Ubuntu and Centos (connectal 15.02.5.1424098179)
